### ISSUE TITLE
[ISSUE] Alarm Manager :: Not Propagating after Reboot

### ISSUE THREAD

**Issue by VersCreativeUKAutomate** [VersCreativeUK/FACETS#11]
Issue migrated to public repo.

When a user reboots their device, any alarms or reminders setup are not triggered. This can only be resolved by opening the application to "reset" the `AlarmManager`

**Comment by davcpas1234** [comment]
This is due to a change in `AlarmManager` since API 23 (Marshmallow) where it is cleared on a boot cycle. 

This can be fixed by adding a `BroadcastReceiver` to handle `android.intent.action.BOOT_COMPLETED` and then reset all reminders and alarms.

**Comment by davcpas1234** [comment]
Functionality has been added to receive a `BOOT_COMPLETED` broadcast and reset all **Rest Periods** reminders. Further development will be required to reset:
- Sleep Wake Pattern Reminders
- Activity Diary Notifications (TBD)

**Comment by davcpas1234** [comment]
Partial Fix to be released into `0.0.7` with follow up with the above areas

**Comment by davcpas1234** [comment]
Sleep Wake Pattern Reminders have been added

**Comment by davcpas1234** [comment]
Closing this as the developed areas have been released into `0.0.7`

I will open a new tracking ticket for the Activity Diary Notifications, once these have been scoped fully.
