### ISSUE TITLE
[ISSUE] TTS NullPointerReference

### ISSUE THREAD

**Issue by andy475uk** [VersCreativeUK/FACETS#113]
**Application Version**
v0.0.12-rc1

**Issue Description**
P303 experienced the following error during unsupervised usability testing - error when selecting Week 1 Recap (see attached screenshot) on Samsung Galaxy J6  

**Steps to Reproduce**
1. Selecting Week 1 Recap
4. See error -  (attached screenshot)  

**Expected Behaviour**
Week 1 recap appears

**Screenshots (Optional)**

![P303_testing_error_20200902_143623](https://user-images.githubusercontent.com/16002574/92120599-2e6cb980-edf1-11ea-80c2-f49d36a8f0c2.jpg)

**Comment by VersCreativeUKAutomate** [comment]
Automated: Bug logged with under reference vcuk/46af96a6d07b95b77835eb86f1a3c932

**Comment by damarie-vcuk** [comment]
@VersCreativeUKAutomate Assign me

**Comment by damarie-vcuk** [comment]
```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'boolean android.speech.tts.TextToSpeech.isSpeaking()' on a null object reference
uk.ac.bournemouth.facets.Activities.MainActivity.stopSpeech (MainActivity.java:1548)
uk.ac.bournemouth.facets.Fragments.ActivityDiary.Week1RecapFragment.stopSpeech (Week1RecapFragment.java:288)
uk.ac.bournemouth.facets.Fragments.ActivityDiary.Week1RecapFragment.access$600 (Week1RecapFragment.java:38)
uk.ac.bournemouth.facets.Fragments.ActivityDiary.Week1RecapFragment$4.onPageSelected (Week1RecapFragment.java:184)
```

**Comment by damarie-vcuk** [comment]
@davcpas1234 can you advise?

**Comment by davcpas1234** [comment]
Not 100% sure @damarie-vcuk. The Week1RecapFragment in my latest code base was replaced with an updated version.

Can you download a copy of the v0.0.12-rc1 from GPS and see if it replicates?

**Comment by damarie-vcuk** [comment]
Just downloaded and tested it with GPS version and I can't reproduce the issue, it may be a manufacturer OEM specific issue, with TTS as Samsung in particular have a on-board TTS engine as opposed to Google TTS engine.

**Comment by andy475uk** [comment]
Have been doing some digging - looking at the survey response data completed yesterday p303 also noted the following in separate improvement/addition suggestions box (although unrelated to visiting week 1 recap):
"I continuously encountered a pop-up "Google TJS Voice" or "Install Voice Data" - could this be a one-off option in Settings?"
If this feature is not installed then it looks like it will error - is there a way that you can bypass the null pointer and put a message up about needing to install the voice feature as a nice to have?

**Comment by damarie-vcuk** [comment]
That would explain the issue, if the device prompts this it normally means that TTS is not installed fully.

I would advise the user to follow the below instructions:

1. Open the **Settings** app.
2. Scroll down and tap **General management**.
3. Tap **Language and input**. It's the first option on the General Management page.
4. Tap **Text-to-speech**. You can find it under the "SPEECH" heading on the Language and Input menu.
![image](https://user-images.githubusercontent.com/70242395/92138818-ccb74a00-ee06-11ea-98fb-fb45943466d7.png)

5. Click the Cog icon next to **Preferred Engine** (**Note: not language as highlighted below**)
![image](https://user-images.githubusercontent.com/70242395/92138878-e22c7400-ee06-11ea-8c6c-eb729c599f83.png)

6. Select the Google text-to-speech engine.
![image](https://user-images.githubusercontent.com/70242395/92138779-bd380100-ee06-11ea-90bd-065362f7f42d.png)


It may then prompt the user the user to install TTS data, they would select **English (UK) or English (US)**:
![image](https://user-images.githubusercontent.com/70242395/92139044-1c961100-ee07-11ea-83e8-eab1dfcc25b8.png)


Once installed, they would just need to restart the FACETS app and that prompt should disappear.

**Comment by damarie-vcuk** [comment]
@davcpas1234 can we add a prompt in the app to avoid a crash?

**Comment by davcpas1234** [comment]
Yep the below to
`MainActivity.java::speakOut(String, AppCompatImageButton, View, View)` and
`MainActivity.java::speakOut(String, MaterialButton)`:

```java
if(tts == null){
    new MaterialDialog.Builder(this)
        .title("Unable to acquire Text to Speech engine")
        .content("Please check your Text-to-Speech settings and try restarting the app.")
        .positiveText("Okay")
        .onPositive((dialog1, which) -> {
            dialog1.dismiss();
        }).neutralText("Text-To-Speech Settings")
        .onNeutral(((dialog, which) -> {
            Intent intent = new Intent();
            intent.setAction("com.android.settings.TTS_SETTINGS");
            intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            startActivity(intent);
        })).show();

    return;
}
```

and the below to `MainActivity.java::stopSpeaking()`:
```java
if(tts == null)
     return;
```

**Comment by VersCreativeUKAutomate** [comment]
Automated: an external access request has been received from @damarie-vcuk to VersCreativeUK/FACETS

**Comment by damarie-vcuk** [comment]
@davcpas1234 thanks, can you authorise the above?

**Comment by davcpas1234** [comment]
@VersCreativeUKAutomate Authorise

**Comment by VersCreativeUKAutomate** [comment]
Automated: Request Authorised by verified account @davcpas1234

**Comment by davcpas1234** [comment]
@VersCreativeUKAutomate Merge PR #114

**Comment by damarie-vcuk** [comment]
Thanks @davcpas1234 - @andy475uk the change has been merged into the codebase which David has authorised my access to. Would you like me to release a new version?

**Comment by davcpas1234** [comment]
@damarie-vcuk I see you started drafting one - thanks. Just leave it like that until confirmed by BU

**Comment by andy475uk** [comment]
Yes, please release a new version. Thanks very much.

**Comment by damarie-vcuk** [comment]
Released. @VCAmyPopple - Can you process on GPC?

**Comment by VCAmyPopple** [comment]
Of course Dani.

**Comment by VCAmyPopple** [comment]
Is this on our GPC? I can't find it?

**Comment by damarie-vcuk** [comment]
Ah! Sorry, my mistake - I'll give you delegate access now

**Comment by damarie-vcuk** [comment]
@VCAmyPopple you should have access now.

**Comment by VCAmyPopple** [comment]
Yep! All released 😊
