### ISSUE TITLE
[ISSUE] MaterialDrawer :: Navigation State on "Up"

### ISSUE THREAD

**Issue by VersCreativeUKAutomate** [VersCreativeUK/FACETS#12]
Issue migrated to public repo.

When a user navigates "up" (back) the current page is not updated in the navigation drawer.

**Comment by davcpas1234** [comment]
Update functions added to drawer interface, test cases are now being run.

**Comment by davcpas1234** [comment]
Bug with "StickyFooter" items raised with developer and workaround implemented.

See: https://github.com/mikepenz/MaterialDrawer/issues/2423

**Comment by davcpas1234** [comment]
Workaround will be released in `0.0.7` awaiting update from developer.

Closing this for now.

**Comment by davcpas1234** [comment]
This has been acknowledged by the developer and will be fixed in a plugin release.
