### ISSUE TITLE
User :: Missing Display Name

### ISSUE THREAD

**Issue by VersCreativeUKAutomate** [VersCreativeUK/FACETS#13]
Issue migrated to public repo.

When an account is created by an admin (via Firebase) there is currently no implemented way to assign a "Display Name" to the user's profile from the Firebase Console. Therefore this will be blank when the user logs into the application.

A popup needs to be added to check this and prompt the user for this information.

**Comment by davcpas1234** [comment]
Added dynamic check to prompt for `displayName()`
