### ISSUE TITLE
MaterialDrawer :: Custom Navigation Implementation

### ISSUE THREAD

**Issue by VersCreativeUKAutomate** [VersCreativeUK/FACETS#2]
Issue migrated to public repo.

### Summary
Currently when a user switches between custom drawer items (those which create additional menu items) when selecting another custom drawer item the changes to the drawer layout are lost, forcing the user to reselect the menu item.

**Comment by davcpas1234** [comment]
Resolved

#### Additional Implementation
Added method to handle custom menu option creation and called this once drawer is reset to ensure any custom menu changes are still propagated.
