### ISSUE TITLE
[ISSUE] Text overlay in Rest & Sleep Routine.

### ISSUE THREAD

**Issue by nan-bmth** [VersCreativeUK/FACETS#33]
**Application Version**
0.0.6-rc3

**Issue Description**
Text overlay in Rest & Sleep Routine

**Steps to Reproduce**

1. Go to drawer and select Rest&Sleep Routine
2. Click on Sleep/Wake tab.
3. It will show "Your sleep & wake pattern is disabled."
4. Click on Rest tab and the text on Step 3 is now overlaid on the top of Rest message.

**Expected Behaviour**
No overlay.

**Screenshots (Optional)**

**Comment by davcpas1234** [comment]
Issue replicated and resolved.

**Comment by davcpas1234** [comment]
Will be released in `v0.0.6-rc4`
