### ISSUE TITLE
[ISSUE] Unable to turn off a rest schedule

### ISSUE THREAD

**Issue by nan-bmth** [VersCreativeUK/FACETS#34]
**Application Version**
0.0.6-rc3

**Issue Description**
A rest schedule can be deleted but it cannot be turned off.

**Steps to Reproduce**
1. In Rest & Sleep Routine, if a rest schedule is set, click Show All.
2. Turn off the schedule.
3. The schedule still shows on the main Rest & Sleep Routine screen and repeat 1 you will see it is still on.

**Expected Behaviour**
The schedule is turned off as expected and the correct message is displayed on the main screen.

**Screenshots (Optional)**

**Comment by davcpas1234** [comment]
Issue replicated

**Comment by davcpas1234** [comment]
Issue Resolved.

**Additional Implementation**:
Added function to determine if next period is enabled and iterator to prevent indefinite loops.

**Comment by davcpas1234** [comment]
Will be released in `v0.0.6-rc4`
