### ISSUE TITLE
[REQUEST] Replace clock with the pie chart in Sleep & Wake Pattern

### ISSUE THREAD

**Issue by nan-bmth** [VersCreativeUK/FACETS#35]
**Is your feature request related to a problem? If so, please describe.**
No

**Describe the feature you would like**
There is no need to display a running clock in Rest & Sleep Routine as the whole purpose is to visualise their planned routine. The pie chart used in setting up Wind up and down pattern is good enough.

**Additional Information**

**Comment by davcpas1234** [comment]
Will look into this and request feedback  from the wider team

**Comment by davcpas1234** [comment]
Changes agreed:
- Remove Clock displays
- Remove View SWR donut
- Replace 'Rest' Clock with Donut chart from 'Rest Summary'
- Replace 'Sleep/Wake' Clock with Donut chart from View SWR edit page
- Replace 'Rest Summary' donut with Overall summary combining both rest periods and sleep/wake routine

**Comment by davcpas1234** [comment]
All changes have been implemented, all will be released in `0.0.7`:

![image](https://user-images.githubusercontent.com/3764587/52958453-0131f500-338c-11e9-9d73-b34005bc6eac.png)

![image](https://user-images.githubusercontent.com/3764587/52958505-17d84c00-338c-11e9-9011-cff6c7b64ae5.png)
![image](https://user-images.githubusercontent.com/3764587/52958506-1870e280-338c-11e9-8d32-375964971e50.png)
