### ISSUE TITLE
[REQUEST] Reminder Type Option Selection

### ISSUE THREAD

**Issue by BUCRU-FACETS** [VersCreativeUK/FACETS#36]
![img_6095](https://user-images.githubusercontent.com/47219064/52492328-d9d76d00-2bc0-11e9-8fea-24b256e46576.JPG)
Would it be possible for the different types of rest reminders to be selected directly from three categories possibly with icons (could be in different colours)?
silent, tone, alarm.  
There could be info buttons that could be clicked on for further more detailed information.  Or it could be set up so you get information when you click on the icon and you can then choose to hide the information.  This would reduce the number of required clicks and make it more intuitive and visual (fewer words - which is helpful for people who are fatigued).
Also could there be an option to 'set as default' so you can set say a silent reminder as your preferred option?

**Comment by davcpas1234** [comment]
see #20
