### ISSUE TITLE
[ISSUE] Icon for Silent Notification Missing

### ISSUE THREAD

**Issue by BUCRU-FACETS** [VersCreativeUK/FACETS#37]
![img_6094](https://user-images.githubusercontent.com/47219064/52493490-7f8bdb80-2bc3-11e9-8e87-756b2f4119df.JPG)

The icon that comes up for a silent reminder (notification) looks like an alarm clock ringing. See 13.30 rest in attached photo.

**Comment by davcpas1234** [comment]
Issue resolved. Will be released in `v0.0.6-rc4`
