### ISSUE TITLE
[REQUEST] Changes to Heatmap display

### ISSUE THREAD

**Issue by BUCRU-FACETS** [VersCreativeUK/FACETS#38]
![img_6092](https://user-images.githubusercontent.com/47219064/52493579-c1b51d00-2bc3-11e9-8e1c-dcdc4c27948a.JPG)

At the left hand and right hand extremities of the Heatmap display if there are no data and it is greyed out it is difficult to differentiate it from the background. Can the grey be made darker?

**Comment by davcpas1234** [comment]
Implemented in `0.0.6-rc4`

**Comment by davcpas1234** [comment]
![screenshot_20190208-171105](https://user-images.githubusercontent.com/3764587/52493936-97b02a80-2bc4-11e9-8cd4-ac6176f519c6.png)
