### ISSUE TITLE
[ISSUE] Sleep and Wake Pattern Layout Integrity

### ISSUE THREAD

**Issue by BUCRU-FACETS** [VersCreativeUK/FACETS#39]
**Application Version**

v0.0.6

**Issue Description**

On the Sleep & Wake Pattern page the 'Wind Down' and 'Wind Up' are in small fonts and 'Not set'
is in a large font. The icons for day and night are quite small.  

[I did mention that for shift workers wind down and wind up won't relate to sunrise and sunset but I think we agreed in our meeting last week that they are generic symbols and it doesn't matter.]

**Screenshots (Optional)**

![img_6096](https://user-images.githubusercontent.com/47219064/52494374-b82cb480-2bc5-11e9-98d1-274c101a48e2.JPG)

**Comment by davcpas1234** [comment]
Updated layout will be released in `v0.0.6-rc4` for feedback
