### ISSUE TITLE
MaterialDrawer :: Unwanted Interaction with Activity Items

### ISSUE THREAD

**Issue by VersCreativeUKAutomate** [VersCreativeUK/FACETS#4]
Issue migrated to public repo.

When a user is viewing their list of activities and attempts to open the drawer, their action causes an unwanted behaviour. The `onLongClickListener()` from the `ActivityList` Fragment is called.

**Comment by davcpas1234** [comment]
Moved from `onLongClick()` interface on the parent `RecyclerView` to itemView `onLongClickListener()` to allow for correct touch interception
