### ISSUE TITLE
[REQUEST] Custom Rest Period Duration Format

### ISSUE THREAD

**Issue by BUCRU-FACETS** [VersCreativeUK/FACETS#40]
**Details**

Do we need rest periods in seconds as well as minutes or will minutes suffice?  It is confusing when you go to put in 25 for 25 minutes and you are actually putting in 25 secs.  Suggest we don't need seconds. Good to keep it simple.  Once people have put in a custom duration will it save custom durations they use frequently?

**Screenshots (Optional)**

![img_6098](https://user-images.githubusercontent.com/47219064/52496561-99c9b780-2bcb-11e9-8472-38db7b9e0e1d.JPG)

**Comment by davcpas1234** [comment]
This format is pre-determined by the available plugin as either HH_MM or MM_SS.

I will change the plugin to accept minutes as the minimum expected value

**Comment by davcpas1234** [comment]
This will be released in `v0.0.6-rc4`
