### ISSUE TITLE
Activity description not scrolling

### ISSUE THREAD

**Issue by BUCRU-FACETS** [VersCreativeUK/FACETS#44]
**Application Version**

V.0.0.6
**Issue Description**
I added an activity 'sitting at desk' then edited it and changed it to 'driving car' and the description wasn't scrolling on the screen - though I wasn't sure whether it was supposed to be scrolling. Now I have added another activity and it still isn't scrolling.
![img_6146](https://user-images.githubusercontent.com/47219064/52644239-5d050580-2ed6-11e9-9167-0f4b132c2932.JPG)
![img_6147](https://user-images.githubusercontent.com/47219064/52644240-5d050580-2ed6-11e9-8e08-d34cbde9289f.JPG)

**Steps to Reproduce**

**Expected Behaviour**

**Screenshots (Optional)**

**Comment by davcpas1234** [comment]
The scrolling behaviour is only triggered when the title is too long to fit into the space provided.

**Comment by davcpas1234** [comment]
![image](https://user-images.githubusercontent.com/3764587/52647475-b07a5200-2edc-11e9-8f69-001830f9ef86.png)
