### ISSUE TITLE
MAJOR - Firestore :: Offline Data Persistence

### ISSUE THREAD

**Issue by VersCreativeUKAutomate** [VersCreativeUK/FACETS#5]
Issue migrated to public repo.

The project implements the offline data persistence cache option available from Firestore. However this is causing a UI bug where the thread is awaiting the completion of the current `Task<Object>` from Firestore.

There is no timeout or completion call if the device is offline as the task is queued asynchronously until the device is online.

This therefore caused issues with the UI as currently the device puts up a "saving..." progress bar (or similar) to confirm to the user that their data has been saved.

**Comment by davcpas1234** [comment]
After multiple attempts to resolve this through `DocumentSnapshot` and `QuerySnapshot` Listeners, I have opted for a `ConnectivityManager` check to ensure the device is connected. If the device is not connected the Firestore Async task is ignored and success is sent to the user by default as offline persistence has a 0.000012% failure rate.
