### ISSUE TITLE
MaterialDrawer :: Locked Item ActionView

### ISSUE THREAD

**Issue by VersCreativeUKAutomate** [VersCreativeUK/FACETS#6]
Issue migrated to public repo.

Since migrating to `MaterialDrawer`, the previous `NavigationDrawerView`'s attribute `actionView` is now ignored and locked elements can no longer be identifier through the `getActionView()` method as this is ignored by `MaterialDrawer`'s `inflate()` helper class.

This is also preventing the user notification "popup" to alert them that this content is currently locked.

**Comment by davcpas1234** [comment]
Implemented additional Class `LockedPrimaryDrawerItem` to handle this and these are now created programmatically vs. infalted via XML
