### ISSUE TITLE
SmileRating :: Colour Customisation and Scroll Behaviour

### ISSUE THREAD

**Issue by VersCreativeUKAutomate** [VersCreativeUK/FACETS#7]
Issue migrated to public repo.

**Enhancement:** Currently the plugin `SmileRating` has not been developed to support multi colour theming. It only supports `normalColor` and `angryColor`. This needs to be updated to support our 5 colour strategy.

**Bug:** When this view is placed inside a `scrollView` unwanted behaviour is displayed when the user attempts to "seek/slide" between items.

**Comment by davcpas1234** [comment]
Implemented custom view `SmileyRating` to inherit base functions and add additional colour customisations and handle `onTouch()` events correctly similar to `SeekBar`
