### ISSUE TITLE
[REQUEST] v0.0.8-1 Goal Planner Realistic Text Box

### ISSUE THREAD

**Issue by andy475uk** [VersCreativeUK/FACETS#85]
**Is your feature request related to a problem? If so, please describe.**
Related to redesign of goal planner

**Describe the feature you would like**
Realistic ideally needs a text box in addition to the Yes/No choice
As an example am trying to add one of the examples from the handbook
Goal is related to husband cooking dinner on a weekday so is goal realistic question is 
Yes but text needs to relate to I will walk away from the cooker so he has to do it....

**Comment by davcpas1234** [comment]
Marking for closure this was descoped as a requirement at our last meeting.

**Comment by davcpas1234** [comment]
Additional text given appears to relate to achievable rather than realistic. However let's discuss this in a F2F
