### ISSUE TITLE
[ISSUE] Github for FACETS is automatically closing unresolved issues opened by AP

### ISSUE THREAD

**Issue by andy475uk** [VersCreativeUK/FACETS#87]
Stale bot is automatically closing an unresolved issue (84) reported after 15 minutes of inactivity

**Comment by andy475uk** [comment]
This might be because of not being raised with labels or being assigned so will try to raise error 84 again

**Comment by andy475uk** [comment]
no. 84 now re-raised as no. 88

**Comment by andy475uk** [comment]
Issue 88 staying open post 15 mins so error caused by raising issue outside of three options with no auto assignment and labels added

**Comment by davcpas1234** [comment]
@VCAmyPopple Can you check this please?
