### ISSUE TITLE
[ISSUE] v0.0.8-1 Goal Planner - Recurring Week Option Not Allowing Input For Day 

### ISSUE THREAD

**Issue by andy475uk** [VersCreativeUK/FACETS#88]
**Application Version**
v0.0.8-1

**Issue Description**
When trying to add day/days for recurring week option the only way to add a goal is when none are selected

**Steps to Reproduce**

1. Go to Goal Planner
2. Click on Add Goal
3. Scroll down to Recurrence Settings
4. Selected Week then try to add days

**Expected Behaviour**
Add days error message saying 'please select goal recurrence days' if one or more selected
Only works to save if no days selected

**Comment by davcpas1234** [comment]
This has been resolved.
