### ISSUE TITLE
[REQUEST] v0.0.8-1 Goal Planner - Input Goals Highlighted in Top Tab

### ISSUE THREAD

**Issue by andy475uk** [VersCreativeUK/FACETS#89]
**Is your feature request related to a problem? If so, please describe.**
Visibility of completed/active/not started goals when on other tab - currently you don't know if there are any showing (a visible marker would be handy)

**Describe the feature you would like**
Is it possible to flag that there are entered goals in one tab when looking at another?

**Priority**
Not essential feature

**Comment by davcpas1234** [comment]
Could you clarify this for me Andy? Are you wanting an indicator that there are goals in each tab?

I'm worried that the redesign will make this more difficult to implement

**Comment by andy475uk** [comment]
This could work the same way as Request [86] dots for activity diary does - e.g. if goals there you get an indication if not showing the tab (this also replicates similar functionality across the various sections).

But happy to wait post redesign and see what it looks like then - and also take majority view at project meeting - but not an essential priority.

**Comment by davcpas1234** [comment]
New Goal Planner UI has now been implemented:

![Screenshot_1566218463](https://user-images.githubusercontent.com/3764587/63266121-2219cb00-c287-11e9-9a69-bf964ad0203a.png)
