### ISSUE TITLE
[REQUEST] v0.0.8-1 Appointment Time - Make same as rest sleep feature

### ISSUE THREAD

**Issue by andy475uk** [VersCreativeUK/FACETS#90]
**Is your feature request related to a problem? If so, please describe.**
Draggable clock is option for adding appointment time - which was previously identified as fiddly when we were designing rest/sleep time entry criteria

**Describe the feature you would like**
Please can we mirror the design from rest/sleep planner for the time entry in this section

**Priority**
Not essential

**Comment by davcpas1234** [comment]
No worries will change
