### ISSUE TITLE
[REQUEST] v0.0.8-1 Cosmetic White rectangular blocks on intro/help pages

### ISSUE THREAD

**Issue by andy475uk** [VersCreativeUK/FACETS#91]
**Is your feature request related to a problem? If so, please describe.**
Cosmetic request - there are small white rectangles at either end of buttons for help and introduction and white line visible inbetween bar for saying how far through you are when selecting help. This looks odd compared to other sections on the Moto.

**Describe the feature you would like**
Can this be redsigned to look more like the other sections maybe make them totally orange with buttons still being clickable (like done at end of recap) 

**Priority**
Not essential

**Comment by davcpas1234** [comment]
I think I'm with you on this, could you send me a screenshot, please?

**Comment by andy475uk** [comment]
Here you go - it does depend on which colour scheme you use.... 
![Screenshot_20190703-145513](https://user-images.githubusercontent.com/16002574/60598542-c5308700-9da4-11e9-8af6-566c4dffe641.png)

**Comment by davcpas1234** [comment]
This is a "by design" issue with the "bookend" rectangles. I will review with the documentation to discover if these can be justified better.

**Comment by davcpas1234** [comment]
Reference to the "by design":
https://material.io/design/components/bottom-navigation.html#specs

**Comment by davcpas1234** [comment]
What I suggest we do to avoid this is adopt a different colour spec (similar to this):
![image](https://user-images.githubusercontent.com/3764587/63172187-07501800-c035-11e9-8e2f-c4d9e012761a.png)

Where 1 is the new "Theme" Colour and then we can use 2/3 to display to display the indicator icon for #86 and #89  (https://material.io/design/components/bottom-navigation.html#theming)

**Comment by davcpas1234** [comment]
This has been resolved:

![Screenshot_1566221054](https://user-images.githubusercontent.com/3764587/63268860-103b2680-c28d-11e9-9f22-d36a432f605d.png)
